trigger:
- main
- develop

resources:
- repo: self

variables:
  buildConfiguration: 'release'
  vmImageName: 'ubuntu-latest'
  artifactName: 'BooksCatalog-CI'

stages:
- stage: Build
  displayName: Build da Web App
  jobs:
  - job: Build
    displayName: Build da Web App em .NET
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: UseDotNet@2
      displayName: Instalar .NET 6
      inputs:
        packageType: 'sdk'
        version: '6.0.x'
    - script: dotnet --version
      displayName: Exibir versão default do .NET
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: './BooksCatalog.sln'
        arguments: '--configuration $(buildConfiguration)'
      displayName: 'dotnet build $(buildConfiguration)'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: "./BooksCatalog.sln"
        arguments: '--configuration $(buildConfiguration)'
      displayName: 'dotnet test $(buildConfiguration)'
    - task: DotNetCoreCLI@2
      displayName: Build + Publish gerando Artifact
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True
