version: '3.4'

services:
  bookscatalog.api:
    image: ${DOCKER_REGISTRY-}bookscatalogapi
    build:
      context: .
      dockerfile: src/BooksCatalog.Api/Dockerfile
    depends_on:
      - bookscatalog.migrations

  bookscatalog.migrations:
    container_name: migrations
    build:
      context: .
      dockerfile: ./Migrations.Dockerfile
    environment:
      ConnectionStrings__DbConnectionString: "Server=bookscatalog.db;Database=BooksCatalog;Trusted_Connection=False;User Id=sa;Password=Your!Str0ngPassw"
    depends_on:
      - bookscatalog.db

  bookscatalog.db:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your!Str0ngPassw"
